services:

  jenkins:
    image: jenkins/jenkins
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
    - 8025:8025
