pipeline{
    agent any

    stages{
        stage('Checkout'){
            steps{
                git url: 'https://github.com/michalantolik/chemik-police.git', branch: 'main'
            }
        }
        stage('Restore'){
            steps{
                sh 'dotnet restore'
            }
        }
        stage('Build'){
            steps{
                sh 'dotnet build'
            }
        }
        stage('Publish'){
            steps{
                sh 'dotnet publish'
            }
        }
    }
}
