pipeline{
    agent any

    stages{
        stage('Hello'){
            echo 'Hello'
        }
        stage('Checkout'){
            steps{
                git url: 'https://github.com/michalantolik/chemik-police.git', branch: 'main'
            }
        }
        stage('World'){
            echo 'World'
        }
    }
}
